apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: storage-oc3-tls
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  secretName: storage-oc3-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - 'storage-oc3.data-container.net'