source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# ruby "3.1.4"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "7.1.3.4"

# Use sqlite3 as the database for Active Record
# gem "sqlite3", "~> 1.4"
gem "pg"
gem "rdf"
gem "rdf-normalize"
gem "json"
gem "json-ld"
gem "puma"
gem "rack-cors"
gem "oydid"
gem 'doorkeeper'
gem 'responders'
gem 'pagy'
gem 'rswag'
gem 'simple_dag'
gem 'statistics'

eval_gemfile 'Gemfile.extend'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  gem 'derailed'
  gem "stackprof"
  gem "sqlite3", '~> 1.4'
  gem 'annotate'
  gem 'rails-erd'
end

